# Generated by Django 4.2 on 2023-04-28 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'permissions': (('change_name', 'can change name of product'),)},
        ),
    ]
