# Generated by Django 4.2 on 2023-05-02 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_alter_contract_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={},
        ),
    ]
